[server]
enableCORS = false
headless = true
port = $PORT
enableXsrfProtection = false

[theme]
primaryColor="#0063B1"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F5F8FF"
textColor="#000000"
font="sans serif"

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[pages]
format = "pages/{page}.py"
